version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Add labels to pull requests for GitHub Actions
    labels:
      - "dependencies"
      - "github-actions"
    # Set a limit for open pull requests
    open-pull-requests-limit: 10
    # Configure commit message prefix to use "chore" instead of "build"
    commit-message:
      prefix: "chore"
